import { GoldenGrid, GoldenBox } from "@gifcommit/golden-grids";
import type { PlacementValue } from "@gifcommit/golden-grids";
import { mount } from "../main";
import { Page } from "../lib/Page";
import { Band } from "../bands/Band";
import { Fact, Figure } from "../lib/boxes";
import { useViewport, pick } from "../lib/viewport";
import { useExpandGroup } from "../lib/expand";
import { GoldenRectangle, Pentagram, KeplerTriangle, Phyllotaxis, GoldenAngle } from "../diagrams";

/**
 * Page IV — Geometry. The article's longest section, and the one this
 * layout system comes from. Each band pairs a figure with the facts the
 * article states about it; the figures are drawn from the mathematics,
 * not copied.
 */
function Rectangle() {
  const viewport = useViewport();
  const x = useExpandGroup();
  const [to, placement] = pick<readonly [number, PlacementValue]>(viewport, {
    mobile: [3, "top"],
    tablet: [4, "left"],
    desktop: [4, "left"],
  });
  return (
    <Band
      id="rectangle"
      title="The golden rectangle"
      lesson="The golden ratio proportions the adjacent sides of a golden rectangle 1 : φ. Removing or adding squares leaves rectangles still proportioned in φ. Such rectangles can be generated by golden spirals, through successive Fibonacci- and Lucas-number-sized squares and quarter circles, and they feature prominently in the geometry of the regular icosahedron and dodecahedron: three golden rectangles, meeting perpendicularly, contain all twelve vertices of the icosahedron."
      note={`from=1 to=${to} · placement="${placement}" · clockwise=false · hero right`}
      kind="rule"
    >
      <GoldenGrid from={1} to={to} placement={placement} clockwise={false} outline="1px solid var(--rule)">
        <GoldenBox {...x.boxProps("rect")}>
          <Figure label="Figure 1" caption="Removing a square from a golden rectangle leaves a golden rectangle. The quarter circles approximate the golden spiral.">
            <GoldenRectangle />
          </Figure>
        </GoldenBox>
        <GoldenBox {...x.boxProps("sides")}>
          <Fact label="Sides" tone="deep" fitClass="fit--num" body={<p>Removing or adding squares leaves rectangles still proportioned in the ratio φ.</p>} source="Golden rectangle"
            expand={{
              group: x, slotKey: "sides", title: "The golden rectangle",
              full: (
                <>
                  <p>The golden ratio proportions the adjacent side lengths of a golden rectangle in 1 : φ ratio. Removing or adding squares from golden rectangles leaves rectangles still proportioned in φ ratio. They can be generated by golden spirals, through successive Fibonacci and Lucas number-sized squares and quarter circles. They feature prominently in the geometry of the regular icosahedron and dodecahedron.</p>
                </>
              ),
              source: "Adapted from the section Golden rectangle.",
              related: [{ href: "./fibonacci.html#sequence", label: "The Fibonacci sequence" }],
            }}
          >1 : φ</Fact>
        </GoldenBox>
        <GoldenBox {...x.boxProps("spiral")}>
          <Fact label="The spiral" tone="red" fitClass="fit--num" body={<p>Grows by φ each quarter-turn.</p>}
            expand={{
              group: x, slotKey: "spiral", title: "The golden spiral",
              full: (
                <>
                  <p>Logarithmic spirals are self-similar spirals where distances covered per turn are in geometric progression. A logarithmic spiral whose radius increases by a factor of the golden ratio for each quarter-turn is called the golden spiral. These spirals can be approximated by quarter-circles that grow by the golden ratio, or their approximations generated from Fibonacci numbers, often depicted inscribed within a spiralling pattern of squares growing in the same ratio.</p>
                  <p>Not all logarithmic spirals are connected to the golden ratio, and not all spirals that are connected to the golden ratio are the same shape as the golden spiral. A different logarithmic spiral, encasing a nested sequence of golden isosceles triangles, grows by the golden ratio for each 108° that it turns, instead of the 90° turning angle of the golden spiral.</p>
                </>
              ),
              source: "Adapted from the section Golden spiral.",
              related: [{ href: "./world.html#disputed", label: "The nautilus shell, which is not one" }],
            }}
          >r = φ^(2θ/π)</Fact>
        </GoldenBox>
        <GoldenBox>
          <Fact label="Solids" body={<p>Three golden rectangles, mutually perpendicular, have the icosahedron's twelve vertices at their corners.</p>}>Icosahedron</Fact>
        </GoldenBox>
      </GoldenGrid>
    </Band>
  );
}

function Pentagon() {
  const viewport = useViewport();
  const x = useExpandGroup();
  const [to, placement] = pick<readonly [number, PlacementValue]>(viewport, {
    mobile: [5, "right"],
    tablet: [5, "bottom"],
    desktop: [5, "bottom"],
  });
  return (
    <Band
      id="pentagon"
      title="Pentagon and pentagram"
      lesson="In a regular pentagon the ratio of a diagonal to a side is the golden ratio, and intersecting diagonals section each other in the golden ratio. The diagonals form a pentagram, a five-pointed star whose geometry is described throughout by φ: each intersection of edges sections the other edges in the golden ratio, and the inner pentagon's side is to the segment bounded by two crossings as 1 to φ. Pentagonal geometry yields φ as 2 cos 36°, as 1 + 2 sin 18°, and as 2 sin 54°."
      note={`from=1 to=${to} · placement="${placement}" · clockwise=true · hero ${viewport === "mobile" ? "top, portrait" : "right, 8:5"}`}
    >
      <GoldenGrid from={1} to={to} placement={placement}>
        <GoldenBox {...x.boxProps("pent")}>
          <Figure label="Figure 2" caption="A regular pentagon and its diagonals. The heavy diagonal and heavy side are in the ratio φ; each crossing divides a diagonal in the ratio φ.">
            <Pentagram />
          </Figure>
        </GoldenBox>
        <GoldenBox {...x.boxProps("diag")}>
          <Fact label="Diagonal to side" tone="ink" fitClass="fit--num" body={<p>By Ptolemy's theorem on the quadrilateral left when one vertex is removed: a² = b² + ab, so a/b = φ.</p>}
            expand={{
              group: x, slotKey: "diag", title: "Pentagon and pentagram",
              full: (
                <>
                  <p>In a regular pentagon the ratio of a diagonal to a side is the golden ratio, while intersecting diagonals section each other in the golden ratio. The golden ratio properties of a regular pentagon can be confirmed by applying Ptolemy's theorem to the quadrilateral formed by removing one of its vertices. If the quadrilateral's long edge and diagonals are a, and short edges are b, then Ptolemy's theorem gives a² = b² + ab. Dividing both sides by ab yields a/b = (a + b)/a = φ.</p>
                  <p>The diagonal segments of a regular pentagon form a pentagram, or five-pointed star polygon, whose geometry is quintessentially described by φ: each intersection of edges sections other edges in the golden ratio.</p>
                </>
              ),
              source: "Adapted from the section Pentagon and pentagram.",
              related: [{ href: "./history.html#chronology", label: "Why the Greeks met it first" }],
            }}
          >a / b = φ</Fact>
        </GoldenBox>
        <GoldenBox>
          <Fact label="From the pentagon" tone="deep" fitClass="fit--num">φ = 2 cos 36°</Fact>
        </GoldenBox>
        <GoldenBox>
          <Fact label="Equivalently" tone="deep" fitClass="fit--num">1 + 2 sin 18°</Fact>
        </GoldenBox>
        <GoldenBox>
          <Fact label="And" fitClass="fit--num">2 sin 54°</Fact>
        </GoldenBox>
      </GoldenGrid>
    </Band>
  );
}

function Kepler() {
  return (
    <Band
      id="kepler"
      title="The Kepler triangle"
      lesson="The Kepler triangle, named after Johannes Kepler, is the unique right triangle with sides in geometric progression, 1 : √φ : φ. Its side lengths are the three Pythagorean means of φ + 1 and φ − 1, and the three squares on its sides have areas in the golden progression 1 : φ : φ². Its acute angles are arcsin (1/φ) ≈ 38.17° and arccos (1/φ) ≈ 51.83°. Pyramidologists have claimed a doubled Kepler triangle as the cross-section of the Great Pyramid; the consensus of modern scholars is against it."
      note='from=1 to=3 · placement="top" · clockwise=false · hero left · 3:2'
      cap="60rem"
      kind="rule"
    >
      <GoldenGrid from={1} to={3} placement="top" clockwise={false} outline="1px solid var(--rule)">
        <GoldenBox>
          <Figure label="Figure 3" caption="The squares on the sides have areas 1, φ and φ²: the sides are 1, √φ and φ, in geometric progression.">
            <KeplerTriangle />
          </Figure>
        </GoldenBox>
        <GoldenBox>
          <Fact label="Smaller angle" tone="deep" fitClass="fit--num" source="arcsin (1/φ)">38.17°</Fact>
        </GoldenBox>
        <GoldenBox>
          <Fact label="Larger angle" tone="red" fitClass="fit--num" source="arccos (1/φ)">51.83°</Fact>
        </GoldenBox>
      </GoldenGrid>
    </Band>
  );
}

function Angle() {
  const viewport = useViewport();
  const [to, placement] = pick<readonly [number, PlacementValue]>(viewport, {
    mobile: [3, "bottom"],
    tablet: [4, "right"],
    desktop: [4, "right"],
  });
  return (
    <Band
      id="angle"
      title="The golden angle"
      lesson="When two angles that sum to 360° have a ratio of φ, the larger is 360° / φ ≈ 222.5° and the smaller, 360° / φ² ≈ 137.5°, is called the golden angle. It occurs in patterns of plant growth as the optimal spacing of leaf shoots around a stem, so that successive leaves do not block sunlight from the leaves below. Placing each point one golden angle further round at a radius proportional to the square root of its index, Vogel's model, reproduces the spiral families seen in a sunflower head."
      note={`from=1 to=${to} · placement="${placement}" · clockwise=false · hero left`}
    >
      <GoldenGrid from={1} to={to} placement={placement} clockwise={false}>
        <GoldenBox>
          <Figure label="Figure 4" caption="Vogel's model: point n at angle n × 137.5° and radius √n. Every twenty-first point is marked, to show one family of spirals.">
            <Phyllotaxis />
          </Figure>
        </GoldenBox>
        <GoldenBox>
          <Figure label="Figure 5" caption="Two angles summing to 360° in the ratio φ.">
            <GoldenAngle />
          </Figure>
        </GoldenBox>
        <GoldenBox>
          <Fact label="Golden angle" tone="red" fitClass="fit--num" source="360° / φ²">137.5°</Fact>
        </GoldenBox>
        <GoldenBox>
          <Fact label="In plants" tone="deep" body={<p>The spacing of leaf shoots around a stem that keeps each from shading the one below.</p>} link={{ href: "./world.html#applications", label: "§ VI" }}>Phyllotaxis</Fact>
        </GoldenBox>
      </GoldenGrid>
    </Band>
  );
}

mount(
  <Page
    current="geometry.html"
    kicker="Wikipedia · Golden ratio · § Geometry"
    title="Geometry"
    standfirst="The golden ratio appears wherever fivefold symmetry does. It is the ratio of a pentagon's diagonal to its side, the proportion of the golden rectangle and the growth factor of the golden spiral, the common ratio of the Kepler triangle's sides, and the divisor of the circle that gives the golden angle found in the arrangement of leaves."
  >
    <Rectangle />
    <Pentagon />
    <Kepler />
    <Angle />
  </Page>
);
